# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: MIT
#
# Some of the following code is generated by ChatGPT with modifications.

"""Functions to deal with math operations."""

from math import isqrt


def find_best_ratio_divisor_pair(n: int) -> tuple[int, int]:
    """Return the best ratio divisor pair of a number."""
    if n < 0:
        return (1, n)

    for i in range(isqrt(n), 0, -1):
        d, r = divmod(n, i)

        if r == 0:
            return (i, d)

    return (0, 0)
