# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: MIT-0

name: Publish to PyPI

on:
  push:
    tags:
      - v*

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      contents: write
      id-token: write
    steps:
      # Setup environment
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@v6

      - name: Build package
        run: uv build

      - name: Upload package to existing release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/legacy_puyo_tools-*

      - name: Publish package
        run: uv publish --trusted-publishing always
